- name: COLLECTIONS AND NAMESPACES
  ansible.builtin.import_tasks: collections_and_namespaces.yml
  when: hub_objects_collections is defined
  tags: hub_config_collections 

- name: REPOSITORIES
  ansible.builtin.import_tasks: repositories.yml
  when: hub_objects_remotes is defined
  tags: hub_config_repositories 
