---
platforms:
  - name: ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_DISPLAY_OK_HOSTS: false
  playbooks:
    converge: ../shared/converge.yml
    cleanup: ../shared/cleanup.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        object_variable_name: 'controller_objects_execution_environments'
        controller_objects_execution_environments: [
          {'name': 'Execution Environment M', 'descr': '',
           'image': '{{ lookup("ansible.builtin.env", "AH_BACKEND_HOSTNAME") |
                        default(lookup("ansible.builtin.env", "AH_HOST"), true) }}/ee-supported-rhel8:latest', 'pull': 'missing'}
        ]
