---
platforms:
  - name: ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_DISPLAY_OK_HOSTS: false
  playbooks:
    converge: ../shared/converge.yml
    cleanup: ../shared/cleanup.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        same_cleanup_playbook: true
        ping_required: true
        object_variable_name: 'controller_settings_jobs'
        controller_settings_jobs: {
                'AWX_ISOLATION_SHOW_PATHS': [],
                'GALAXY_IGNORE_CERTS': true
        }
