- name: SETTINGS - Get current authenticators (2.5)
  ansible.builtin.set_fact:
    controller_authentication_current: "{{ controller_authentication_current | default([]) +
                                  [{'name': item.name,
                                    'type': item.type,
                                    'enabled': item.enabled,
                                    'configuration': item.configuration}] }}"
  loop: "{{ lookup('ansible.platform.gateway_api', 'authenticators',
                   return_objects=false,
                   host=lookup('ansible.builtin.env', 'GATEWAY_HOSTNAME'),
                   username=lookup('ansible.builtin.env', 'GATEWAY_USERNAME'),
                   password=lookup('ansible.builtin.env', 'GATEWAY_PASSWORD'),
                   verify_ssl=lookup('ansible.builtin.env', 'GATEWAY_VERIFY_SSL'),
                   errors='ignore').results }}"
  loop_control:
    label: " | authenticator: {{ item.name }}"

- name: SETTINGS - Notify on rogue authenticators (2.5)
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        item.type != 'ansible_base.authentication.authenticator_plugins.local' and
        controller_authentication | default([]) | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ controller_authentication_current | default([]) }}"
  loop_control:
    label: " | authenticator: {{ item.name }}"

- name: SETTINGS - Remove rogue authenticators (2.5)
  ansible.platform.authenticator:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        item.type != 'ansible_base.authentication.authenticator_plugins.local' and
        controller_authentication | default([]) | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ controller_authentication_current | default([]) }}"
  loop_control:
    label: " | authenticator: {{ item.name }}"
