- name: CREDENTIALS - Get all credentials from AAP
  ansible.controller.export:
    credentials: 'all'
  register: aap_credentials

- name: CREDENTIALS - Notify on rogue organizational credentials
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        item.organization and
        controller_objects_credentials_organizational | selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.organization.name) | length == 0
  changed_when: true
  loop: "{{ aap_credentials.assets.credentials }}"
  loop_control:
    label: " | credential: {{ item.name }} <- owned by: {{ item.organization.name | default('a user') }}"

- name: CREDENTIALS - Delete rogue organizational credentials
  ansible.controller.credential:
    name: "{{ item.name }}"
    credential_type: "{{ item.credential_type.name }}"
    organization: "{{ item.organization.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        item.organization and
        controller_objects_credentials_organizational | selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.organization.name) | length == 0
  loop: "{{ aap_credentials.assets.credentials }}"
  loop_control:
    label: " | credential: {{ item.name }} <- owned by: {{ item.organization.name | default('a user') }}"

- name: CREDENTIALS - Notify on rogue personal credentials
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        not item.organization and
        controller_objects_credentials_personal | default([]) | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_credentials.assets.credentials }}"
  loop_control:
    label: " | credential: {{ item.name }} <- owned by: {{ item.organization.name | default('a user') }}"

- name: CREDENTIALS - Delete rogue personal credentials
  ansible.controller.credential:
    name: "{{ item.name }}"
    credential_type: "{{ item.credential_type.name }}"
    user: "{{ item.user.username | default('') }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        not item.organization and
        controller_objects_credentials_personal | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_credentials.assets.credentials }}"
  loop_control:
    label: " | credential: {{ item.name }} <- owned by: {{ item.organization.name | default('a user') }}"
  ignore_errors: true # noqa: ignore-errors
