- name: CREDENTIALS - Get all credentials from AAP
  ansible.builtin.set_fact:
    aap_credentials: "{{ aap_credentials | default([]) +
                         [{'name': item.name,
                           'org': item.summary_fields.organization.name | default(''),
                           'type': item.summary_fields.credential_type.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'credentials/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | credential: {{ item.name }}"
  when: not item.managed

- name: CREDENTIALS - Notify on rogue credentials
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_credentials | selectattr("name", "equalto", item.name) |
           selectattr("type", "equalto", item.type) | length == 0
  changed_when: true
  loop: "{{ aap_credentials | default([]) }}"
  loop_control:
    label: " | credential: {{ item.name }} }}"

- name: CREDENTIALS - Delete rogue credentials
  ansible.controller.credential:
    name: "{{ item.name }}"
    credential_type: "{{ item.type }}"
    organization: "{{ omit if not item.org else item.org }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_credentials | selectattr("name", "equalto", item.name) |
           selectattr("type", "equalto", item.type) | length == 0
  loop: "{{ aap_credentials | default([]) }}"
  loop_control:
    label: " | credential: {{ item.name }} }}"
