- name: CREDENTIAL TYPES - Create or modify credential types
  ansible.controller.credential_type:
    name: "{{ item.name }}"
    description: "{{ item.descr }}"
    kind: cloud
    inputs: "{{ item.inputs }}"
    injectors: "{{ item.injectors }}"
  loop: "{{ controller_objects_credential_types | default([]) }}"
  loop_control:
    label: " | credential type: {{ item.name }}"
