- name: CREDENTIAL TYPES - Get all credential types from AAP
  ansible.builtin.set_fact:
    aap_credential_types: "{{ aap_credential_types | default([]) + [{'name': item.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'credential_types/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | credential type: {{ item.name }}"
  when: not item.managed

- name: CREDENTIAL TYPES - Notify on rogue credential types
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_credential_types | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_credential_types | default([]) }}"
  loop_control:
    label: " | credential type: {{ item.name }}"

- name: CREDENTIAL TYPES - Delete rogue credential types
  ansible.controller.credential_type:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_credential_types | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_credential_types | default([]) }}"
  loop_control:
    label: " | credential type: {{ item.name }}"
