- name: EXECUTION ENVIRONMENTS - Get all execution environments from AAP
  ansible.builtin.set_fact:
    aap_ee: "{{ aap_ee | default([]) + [{'name': item.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'execution_environments/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | ee: {{ item.name }}"

- name: EXECUTION ENVIRONMENTS - Notify on rogue execution environments
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_execution_environments | selectattr("name", "equalto", item.name) | length == 0 and
        item.name != 'Control Plane Execution Environment'
  changed_when: true
  loop: "{{ aap_ee | default([]) }}"
  loop_control:
    label: " | ee: {{ item.name }}"

- name: EXECUTION ENVIRONMENTS - Delete rogue execution environments
  ansible.controller.execution_environment:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_execution_environments | selectattr("name", "equalto", item.name) | length == 0 and
        item.name != 'Control Plane Execution Environment'
  loop: "{{ aap_ee | default([]) }}"
  loop_control:
    label: " | ee: {{ item.name }}"
