- name: NOTIFICATIONS - Get all notification profiles from AAP
  ansible.builtin.set_fact:
    aap_notifications: "{{ aap_notifications | default([]) +
                           [{'name': item.name,
                             'notification_type': item.notification_type,
                             'org': item.summary_fields.organization.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'notification_templates/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | notification: {{ item.name }}"
  when: >
        limit_organizations is not defined or
        (limit_organizations is defined and
         item.summary_fields.organization.name | default('') in limit_organizations)

- name: NOTIFICATIONS - Notify on rogue notification profiles
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_notification_profiles | selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.org) | length == 0
  changed_when: true
  loop: "{{ aap_notifications | default([]) }}"
  loop_control:
    label: " | notification: {{ item.name }} <- org: {{ item.org }}"

- name: NOTIFICATIONS - Delete rogue notification profiles
  ansible.controller.notification_template:
    name: "{{ item.name }}"
    notification_type: "{{ item.notification_type }}"
    organization: "{{ item.org }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_notification_profiles | selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.org) | length == 0
  loop: "{{ aap_notifications | default([]) }}"
  loop_control:
    label: " | notification: {{ item.name }} <- org: {{ item.org }}"
