- name: PROJECTS - Get all projects from AAP
  ansible.builtin.set_fact:
    aap_projects: "{{ aap_projects | default([]) + [{'name': item.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'projects/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | project: {{ item.name }}"

- name: PROJECTS - Notify on rogue projects
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_projects | default([]) | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_projects | default([]) }}"
  loop_control:
    label: " | project: {{ item.name }}"

- name: PROJECTS - Delete rogue projects
  ansible.controller.project:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_projects | default([]) | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_projects | default([]) }}"
  loop_control:
    label: " | project: {{ item.name }}"
