- name: PROJECTS - Create or modify projects
  block:
    - name: PROJECTS - Create or modify projects
      ansible.controller.project:
        name: "{{ item.name }}"
        scm_type: "{{ item.type }}"
        scm_branch: "{{ item.branch }}"
        scm_clean: "{{ item.scm_clean }}"
        scm_delete_on_update: "{{ item.scm_delete }}"
        scm_update_on_launch: "{{ item.scm_update }}"
        organization: "{{ item.org }}"
        credential: "{{ item.cred | default(omit) }}"
        scm_url: "{{ item.url }}"
        wait: "{{ wait_project_sync | default(false) }}"
        notification_templates_error: "{{ item.notifications_on_failure }}"
        notification_templates_started: "{{ item.notifications_on_start }}"
        notification_templates_success: "{{ item.notifications_on_success }}"
      loop: "{{ controller_objects_projects | default([]) }}"
      loop_control:
        label: " | project: {{ item.name }}"
      register: projects_change_result
      failed_when: >
                   (not ansible_check_mode and
                    projects_change_result.msg is defined) or
                   (ansible_check_mode and
                    projects_change_result.msg is defined and
                    'expected 1' not in projects_change_result.msg)
      changed_when: >
                    projects_change_result.changed or
                    (projects_change_result.msg is defined and
                     'Project update failed' in projects_change_result.msg) or
                    (ansible_check_mode and
                     projects_change_result.msg is defined and
                     'expected 1' in projects_change_result.msg)

  rescue:
    - name: Fail if error was not related to project sync
      ansible.builtin.fail:
        msg: "Check errors above."
      when: >
            projects_change_result.results |
              selectattr('msg', 'defined') |
                selectattr('msg', '!=', 'Project update failed') | length !=0

    - name: Continue if error happened because project sync failed
      ansible.builtin.debug:
        msg: "Continuing with automation. Check errors above."
