- name: ROLES - Instance groups
  when: controller_objects_roles_instance_groups is defined
  tags:
    - controller_config_roles_instance_groups
    - controller_config_roles_instance_groups_apply
  block:
    - name: ROLES - Create or modify instance group roles (teams)
      ansible.controller.role:
        team: "{{ item.team }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        instance_groups: "{{ item.ig }}"
      loop: "{{ controller_objects_roles_instance_groups | default([]) }}"
      loop_control:
        label: " | team: {{ item.team | default('N/A') }} ->
                   role: {{ item.role }} ->
                   ig: {{ item.ig }}"
      when: item.team is defined
      register: instance_group_roles_teams_change
      failed_when: >
                   (not ansible_check_mode and
                    instance_group_roles_teams_change.msg is defined) or
                   (ansible_check_mode and
                    instance_group_roles_teams_change.msg is defined and
                    'missing items' not in instance_group_roles_teams_change.msg and
                    'returned 0 items' not in instance_group_roles_teams_change.msg)
      changed_when: >
                    instance_group_roles_teams_change.changed or
                    (ansible_check_mode and
                     instance_group_roles_teams_change.msg is defined and
                     ('returned 0 items' in instance_group_roles_teams_change.msg or
                      'missing items' in instance_group_roles_teams_change.msg))
      tags:
        - controller_config_roles_instance_groups_teams
        - controller_config_roles_instance_groups_teams_apply

    - name: ROLES - Create or modify instance group roles (users)
      ansible.controller.role:
        user: "{{ item.user }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        instance_groups: "{{ item.ig }}"
      loop: "{{ controller_objects_roles_instance_groups | default([]) }}"
      loop_control:
        label: " | user: {{ item.user | default('N/A') }} ->
                   role: {{ item.role }} ->
                   ig: {{ item.ig }}"
      when: item.user is defined
      register: instance_group_roles_users_change
      failed_when: >
                   (not ansible_check_mode and
                    instance_group_roles_users_change.msg is defined) or
                   (ansible_check_mode and
                    instance_group_roles_users_change.msg is defined and
                    'returned 0 items' not in instance_group_roles_users_change.msg and
                    'missing items' not in instance_group_roles_users_change.msg)
      changed_when: >
                    instance_group_roles_users_change.changed or
                    (ansible_check_mode and
                     instance_group_roles_users_change.msg is defined and
                     ('returned 0 items' in instance_group_roles_users_change.msg or
                      'missing items' in instance_group_roles_users_change.msg))
      tags:
        - controller_config_roles_instance_groups_users
        - controller_config_roles_instance_groups_users_apply

- name: ROLES - Organizations
  when: controller_objects_roles_organization is defined
  tags:
    - controller_config_roles_orgs
    - controller_config_roles_orgs_apply
  block:
    - name: ROLES - Create or modify organization roles (teams)
      ansible.controller.role:
        team: "{{ item.team }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        organization: "{{ item.org }}"
      loop: "{{ controller_objects_roles_organization | default([]) }}"
      loop_control:
        label: " | team: {{ item.team | default('N/A') }} ->
                   role: {{ item.role }} ->
                   org: {{ item.org }}"
      when: item.team is defined
      register: organization_roles_teams_change
      failed_when: >
                   (not ansible_check_mode and
                    organization_roles_teams_change.msg is defined) or
                   (ansible_check_mode and
                    organization_roles_teams_change.msg is defined and
                    'returned 0 items' not in organization_roles_teams_change.msg and
                    'missing items' not in organization_roles_teams_change.msg)
      changed_when: >
                    organization_roles_teams_change.changed or
                    (ansible_check_mode and
                     organization_roles_teams_change.msg is defined and
                     ('returned 0 items' in organization_roles_teams_change.msg or
                      'missing items' in organization_roles_teams_change.msg))
      tags:
        - controller_config_roles_orgs_teams
        - controller_config_roles_orgs_teams_apply

    - name: ROLES - Create or modify organization roles (users)
      ansible.controller.role:
        user: "{{ item.user }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        organization: "{{ item.org }}"
      loop: "{{ controller_objects_roles_organization | default([]) }}"
      loop_control:
        label: " | user: {{ item.user | default('N/A') }} ->
                   role: {{ item.role }} ->
                   org: {{ item.org }}"
      when: item.user is defined
      register: organization_roles_users_change
      failed_when: >
                   (not ansible_check_mode and
                    organization_roles_users_change.msg is defined) or
                   (ansible_check_mode and
                    organization_roles_users_change.msg is defined and
                    'returned 0 items' not in organization_roles_users_change.msg and
                    'missing items' not in organization_roles_users_change.msg)
      changed_when: >
                    organization_roles_users_change.changed or
                    (ansible_check_mode and
                     organization_roles_users_change.msg is defined and
                     ('returned 0 items' in organization_roles_users_change.msg or
                      'missing items' in organization_roles_users_change.msg))
      tags:
        - controller_config_roles_orgs_users
        - controller_config_roles_orgs_users_apply

- name: ROLES - Credentials
  when: controller_objects_roles_credential is defined
  tags:
    - controller_config_roles_creds
    - controller_config_roles_creds_apply
  block:
    - name: ROLES - Create or modify credential roles (teams)
      ansible.controller.role:
        team: "{{ item.team }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        credentials: "{{ item.cred }}"
      loop: "{{ controller_objects_roles_credential | default([]) }}"
      loop_control:
        label: " | team: {{ item.team | default('N/A') }} ->
                   role: {{ item.role }} ->
                   credential: {{ item.cred }}"
      when: item.team is defined
      register: credential_roles_teams_change
      failed_when: >
                   (not ansible_check_mode and
                    credential_roles_teams_change.msg is defined) or
                   (ansible_check_mode and
                    credential_roles_teams_change.msg is defined and
                    'returned 0 items' not in credential_roles_teams_change.msg and
                    'missing items' not in credential_roles_teams_change.msg)
      changed_when: >
                    credential_roles_teams_change.changed or
                    (ansible_check_mode and
                     credential_roles_teams_change.msg is defined and
                     ('returned 0 items' in credential_roles_teams_change.msg or
                      'missing items' in credential_roles_teams_change.msg))
      tags:
        - controller_config_roles_creds_teams
        - controller_config_roles_creds_teams_apply

    - name: ROLES - Create or modify credential roles (users)
      ansible.controller.role:
        user: "{{ item.user }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        credential: "{{ item.cred }}"
      loop: "{{ controller_objects_roles_credential | default([]) }}"
      loop_control:
        label: " | user: {{ item.user | default('N/A') }} ->
                   role: {{ item.role }} ->
                   credential: {{ item.cred }}"
      when: item.user is defined
      register: credential_roles_users_change
      failed_when: >
                   (not ansible_check_mode and
                    credential_roles_users_change.msg is defined) or
                   (ansible_check_mode and
                    credential_roles_users_change.msg is defined and
                    'returned 0 items' not in credential_roles_users_change.msg and
                    'missing items' not in credential_roles_users_change.msg)
      changed_when: >
                    credential_roles_users_change.changed or
                    (ansible_check_mode and
                     credential_roles_users_change.msg is defined and
                     ('returned 0 items' in credential_roles_users_change.msg or
                      'missing items' in credential_roles_users_change.msg))
      tags:
        - controller_config_roles_creds_users
        - controller_config_roles_creds_users_apply

- name: ROLES - Credentials
  when: controller_objects_roles_credential is defined
  tags:
    - controller_config_roles_templates
    - controller_config_roles_templates_apply
  block:
    - name: ROLES - Create or modify template roles (teams)
      ansible.controller.role:
        team: "{{ item.team }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        job_templates: "{{ item.template }}"
      loop: "{{ controller_objects_roles_template | default([]) }}"
      loop_control:
        label: " | team: {{ item.team | default('N/A') }} ->
                   role: {{ item.role }} ->
                   template: {{ item.template }}"
      when: item.team is defined
      register: templates_roles_teams_change
      failed_when: >
                   (not ansible_check_mode and
                    templates_roles_teams_change.msg is defined) or
                   (ansible_check_mode and
                    templates_roles_teams_change.msg is defined and
                    'returned 0 items' not in templates_roles_teams_change.msg and
                    'missing items' not in templates_roles_teams_change.msg)
      changed_when: >
                    templates_roles_teams_change.changed or
                    (ansible_check_mode and
                     templates_roles_teams_change.msg is defined and
                     ('returned 0 items' in templates_roles_teams_change.msg or
                      'missing items' in templates_roles_teams_change.msg))
      tags:
        - controller_config_roles_templates_teams
        - controller_config_roles_templates_teams_apply

    - name: ROLES - Create or modify template roles (users)
      ansible.controller.role:
        user: "{{ item.user }}"
        role: "{{ item.role | lower | replace(' ', '_') | replace('approve', 'approval') }}"
        job_template: "{{ item.template }}"
      loop: "{{ controller_objects_roles_template | default([]) }}"
      loop_control:
        label: " | user: {{ item.user | default('N/A') }} ->
                   role: {{ item.role }} ->
                   template: {{ item.template }}"
      when: item.user is defined
      register: templates_roles_users_change
      failed_when: >
                   (not ansible_check_mode and
                    templates_roles_users_change.msg is defined) or
                   (ansible_check_mode and
                    templates_roles_users_change.msg is defined and
                    'returned 0 items' not in templates_roles_users_change.msg and
                    'missing items' not in templates_roles_users_change.msg)
      changed_when: >
                    templates_roles_users_change.changed or
                    (ansible_check_mode and
                     templates_roles_users_change.msg is defined and
                     ('returned 0 items' in templates_roles_users_change.msg or
                      'missing items' in templates_roles_users_change.msg))
      tags:
        - controller_config_roles_templates_users
        - controller_config_roles_templates_users_apply
