- name: SCHEDULES - Get all schedules from AAP
  ansible.controller.export:
    schedules: 'all'
  register: aap_schedules

- name: SCHEDULES - Notify on rogue schedules
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_schedules | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_schedules.assets.schedules }}"
  loop_control:
    label: " | schedule: {{ item.name }}"

- name: SCHEDULES - Delete rogue schedules
  ansible.controller.schedule:
    name: "{{ item.name }}"
    unified_job_template: "{{ item.unified_job_template.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_schedules | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_schedules.assets.schedules }}"
  loop_control:
    label: " | schedule: {{ item.name }}"
