- name: SCHEDULES - Filter schedules if org limit is specified
  ansible.builtin.set_fact:
    controller_objects_schedules: "{{ controller_objects_schedules | default([]) | selectattr('template', 'in', unified_templates_in_orgs) }}"
  when: limit_organizations is defined
  vars:
    unified_templates_in_orgs: "{{ lookup('ansible.controller.controller_api',
                                          'unified_job_templates/',
                                          return_objects=false,
                                          return_all=true).results |
                                   selectattr('summary_fields.organization.name', 'defined') |
                                   selectattr('summary_fields.organization.name', 'in', limit_organizations) |
                                   map(attribute='name') }}"

- name: SCHEDULES - Create or modify schedules
  ansible.controller.schedule:
    name: "{{ item.name }}"
    description: "{{ item.descr }}"
    unified_job_template: "{{ item.template }}"
    rrule: "{{ item.rules }}"
  loop: "{{ controller_objects_schedules | default([]) }}"
  loop_control:
    label: " | schedule: {{ item.name }}"
  register: schedules_change_result
  failed_when: >
               (not ansible_check_mode and
                schedules_change_result.exception is defined) or
               (ansible_check_mode and
                schedules_change_result.exception is defined and
                'object is not subscriptable' not in schedules_change_result.exception)
  changed_when: >
                schedules_change_result.changed or
                (ansible_check_mode and
                 schedules_change_result.exception is defined and
                 'object is not subscriptable' in schedules_change_result.exception)
