- name: TEAMS - Get all teams from AAP
  ansible.builtin.set_fact:
    aap_teams: "{{ aap_teams | default([]) +
                   [{'name': item.name,
                     'org': item.summary_fields.organization.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'teams/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | team: {{ item.name }}"

- name: TEAMS - Notify on rogue teams
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_teams |
          selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.org) | length == 0
  changed_when: true
  loop: "{{ aap_teams | default([]) }}"
  loop_control:
    label: " | team: {{ item.name }}"

- name: TEAMS - Delete rogue teams (pre 2.5)
  ansible.controller.team:
    name: "{{ item.name }}"
    organization: "{{ item.org }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_ping.version is version_compare('4.6', '<') and
        controller_objects_teams |
          selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.org) | length == 0
  loop: "{{ aap_teams | default([]) }}"
  loop_control:
    label: " | team: {{ item.name }}"

- name: TEAMS - Delete rogue teams (2.5)
  ansible.platform.team:
    name: "{{ item.name }}"
    organization: "{{ item.org }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_ping.version is version_compare('4.6', '>=') and
        controller_objects_teams |
          selectattr("name", "equalto", item.name) |
          selectattr("org", "equalto", item.org) | length == 0
  loop: "{{ aap_teams | default([]) }}"
  loop_control:
    label: " | team: {{ item.name }}"
