- name: TEMPLATES - Get all templates from AAP
  ansible.builtin.set_fact:
    aap_templates: "{{ aap_templates | default([]) + [{'name': item.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'job_templates/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | template: {{ item.name }}"

- name: TEMPLATES - Notify on rogue templates
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_templates | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_templates | default([]) }}"
  loop_control:
    label: " | template: {{ item.name }}"

- name: TEMPLATES - Delete rogue templates
  ansible.controller.job_template:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_templates | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_templates | default([]) }}"
  loop_control:
    label: " | template: {{ item.name }}"
