- name: WORKFLOWS - Get all workflows from AAP
  ansible.builtin.set_fact:
    aap_workflows: "{{ aap_workflows | default([]) + [{'name': item.name}] }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'workflow_job_templates/', return_objects=false, return_all=true).results }}"
  loop_control:
    label: " | workflow: {{ item.name }}"

- name: WORKFLOWS - Notify on rogue workflows
  ansible.builtin.debug:
    msg: "Shouldn't be there"
  when: >
        not delete_objects | default(false) | bool and
        controller_objects_workflows | selectattr("name", "equalto", item.name) | length == 0
  changed_when: true
  loop: "{{ aap_workflows | default([]) }}"
  loop_control:
    label: " | workflow: {{ item.name }}"

- name: WORKFLOWS - Delete rogue workflows
  ansible.controller.workflow_job_template:
    name: "{{ item.name }}"
    state: absent
  when: >
        delete_objects | default(false) | bool and
        controller_objects_workflows | selectattr("name", "equalto", item.name) | length == 0
  loop: "{{ aap_workflows | default([]) }}"
  loop_control:
    label: " | workflow: {{ item.name }}"
