---
platforms:
  - name: ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_DISPLAY_OK_HOSTS: false
  playbooks:
    converge: ../shared/converge.yml
    cleanup: ../shared/cleanup.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        ping_required: true
        object_variable_name: 'controller_objects_organizations'
        controller_objects_organizations: [
          {'name': 'Org M', 'descr': '', 'creds': []},
          {'name': 'Default', 'descr': '', 'creds': ['Ansible Galaxy']}
        ]
