---
platforms:
  - name: ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_DISPLAY_OK_HOSTS: false
  playbooks:
    converge: ../shared/converge.yml
    cleanup: ../shared/cleanup.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        object_variable_name: 'controller_objects_credential_types'
        controller_objects_credential_types:
          - name: 'Credential Type M'
            descr: ''
            inputs:
              fields:
                - id: 'passwordM'
                  type: 'string'
                  label: 'Password'
            injectors:
              extra_vars:
                pass: "{% raw %}{{ '{{ passwordM }}' }}{% endraw %}"
