---
platforms:
  - name: ansible

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_DISPLAY_OK_HOSTS: false
  playbooks:
    converge: ../shared/converge.yml
    cleanup: ../shared/cleanup.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        object_variable_name: 'controller_objects_instance_groups'
        controller_objects_instance_groups: [
          {'name': 'Instance Group M', 'minimum': 1, 'percentage': 0,
           'instances': []},
          {'name': 'default', 'minimum': 0, 'percentage': 100,
           'instances': []}
        ]
