---
- name: CREDENTIAL TYPES - Audit AAP credential types
  hosts: localhost
  gather_facts: false

  tasks:
    - name: CREDENTIAL TYPES - Build credential types list
      ansible.builtin.set_fact:
        controller_objects_credential_types: "{{ controller_objects_credential_types | default([]) +
                                                 [{'name': item.name,
                                                   'descr': item.description,
                                                   'inputs': item.inputs,
                                                   'injectors': item.injectors} | regex_replace('\n', '')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'credential_types/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | credential type: {{ item.name }}"
      when: not item.managed

    - name: CREDENTIAL TYPES - Show credential types (formatted)
      ansible.builtin.debug:
        var: controller_objects_credential_types
      when: >
            controller_objects_credential_types is defined and
            controller_objects_credential_types
