---
- name: CREDENTIAL TYPES - Audit AAP credential types
  hosts: localhost
  gather_facts: false

  tasks:
    - name: CREDENTIAL TYPES - Get all credential types from AAP
      ansible.controller.export:
        credential_types: 'all'
      register: aap_credential_types

    - name: CREDENTIAL TYPES - Build credential types list
      ansible.builtin.set_fact:
        controller_objects_credential_types: "{{ controller_objects_credential_types | default([]) +
                                                 [{'name': item.name,
                                                   'descr': item.description,
                                                   'inputs': item.inputs,
                                                   'injectors': item.injectors} | regex_replace('\n', '')] }}"
      loop: "{{ aap_credential_types.assets.credential_types }}"
      loop_control:
        label: " | credential type: {{ item.name }}"

    - name: CREDENTIAL TYPES - Show credential types
      ansible.builtin.debug:
        var: controller_objects_credential_types
      when: >
            controller_objects_credential_types is defined and
            controller_objects_credential_types
