---
- name: NOTIFICATIONS - Audit notification profiles
  hosts: localhost
  gather_facts: false

  tasks:
    - name: NOTIFICATIONS - Build list with all notification profiles
      ansible.builtin.set_fact:
        controller_objects_notification_profiles: "{{ controller_objects_notification_profiles | default([]) +
                                                      [{'name': item.name,
                                                        'descr': item.description,
                                                        'notification_type': item.notification_type,
                                                        'notification_config': item.notification_configuration,
                                                        'org': item.summary_fields.organization.name,
                                                        'messages': {} if not item.messages else item.messages} |
                                                         regex_replace('\n', '')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'notification_templates/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | notification: {{ item.name }}"

    - name: NOTIFICATIONS - Show notification profiles (formatted)
      ansible.builtin.debug:
        var: controller_objects_notification_profiles
      when: >
            controller_objects_notification_profiles | default('') and
            not show_vars_at_the_end | default(false)
