---
- name: PROJECTS - Audit AAP projects
  hosts: localhost
  gather_facts: false

  tasks:
    - name: PROJECTS - Build list with all projects
      ansible.builtin.set_fact:
        controller_objects_projects: |
                                      {% if item.summary_fields.credential is not defined %}
                                      {{ controller_objects_projects | default([]) +
                                         [{'name': item.name,
                                           'type': item.scm_type,
                                           'branch': item.scm_branch,
                                           'scm_clean': item.scm_clean,
                                           'scm_delete': item.scm_delete_on_update,
                                           'scm_update': item.scm_update_on_launch,
                                           'org': item.summary_fields.organization.name | default(''),
                                           'url': item.scm_url} | regex_replace('\n', '')] }}
                                      {% else %}
                                      {{ controller_objects_projects | default([]) +
                                         [{'name': item.name,
                                           'type': item.scm_type,
                                           'branch': item.scm_branch,
                                           'scm_clean': item.scm_clean,
                                           'scm_delete': item.scm_delete_on_update,
                                           'scm_update': item.scm_update_on_launch,
                                           'org': item.summary_fields.organization.name | default(''),
                                           'cred': item.summary_fields.credential.name,
                                           'url': item.scm_url} | regex_replace('\n', '')] }}
                                      {% endif %}
      loop: "{{ lookup('ansible.controller.controller_api', 'projects/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | project: {{ item.name }}"

    - name: PROJECTS - Show projects (formatted)
      ansible.builtin.debug:
        var: controller_objects_projects
      when: >
            controller_objects_projects is defined and
            controller_objects_projects
