---
- name: CREDENTIALS - Audit AAP credentials
  hosts: localhost
  gather_facts: false

  tasks:
    - name: CREDENTIALS - Get all credentials from AAP
      ansible.controller.export:
        credentials: 'all'
      register: aap_credentials

    - name: CREDENTIALS - Get all credentials sources
      ansible.builtin.set_fact:
        aap_credential_sources: "{{ lookup('ansible.controller.controller_api', 'credential_input_sources/', return_objects=false, return_all=true).results }}"

    - name: CREDENTIALS - Build credentials list owned by organization
      ansible.builtin.set_fact:
        controller_objects_credentials_organizational: "{{ controller_objects_credentials_organizational | default([]) +
                                                           [{'name': item.name,
                                                             'org': item.organization.name,
                                                             'descr': item.description,
                                                             'type': item.credential_type.name,
                                                             'inputs': item.inputs,
                                                             'src_input_field_name': aap_credential_sources |
                                                                                     selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                                     map(attribute='input_field_name') | last | default(''),
                                                             'src_credential': aap_credential_sources |
                                                                               selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                               map(attribute='summary_fields.source_credential.name') | last | default(''),
                                                             'src_metadata':  aap_credential_sources |
                                                                              selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                              map(attribute='metadata') | last | default('')} |
                                                            regex_replace('\n', '') | replace('$encrypted$', 'HIDDEN')] }}"
      when: item.organization
      loop: "{{ aap_credentials.assets.credentials }}"
      loop_control:
        label: " | credential: {{ item.name }}"

    - name: CREDENTIALS - Build credentials list owned by user
      ansible.builtin.set_fact:
        controller_objects_credentials_personal: "{{ controller_objects_credentials_personal | default([]) +
                                                     [{'name': item.name,
                                                       'user': item.user.username | default(''),
                                                       'descr': item.description,
                                                       'type': item.credential_type.name,
                                                       'inputs': item.inputs,
                                                       'src_input_field_name': aap_credential_sources |
                                                                               selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                               map(attribute='input_field_name') | last | default(''),
                                                       'src_credential': aap_credential_sources |
                                                                         selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                         map(attribute='summary_fields.source_credential.name') | last | default(''),
                                                       'src_metadata':  aap_credential_sources |
                                                                        selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                        map(attribute='metadata') | last | default('')} |
                                                      regex_replace('\n', '') | replace('$encrypted$', 'HIDDEN')] }}"
      when: not item.organization
      loop: "{{ aap_credentials.assets.credentials }}"
      loop_control:
        label: " | credential: {{ item.name }}"

    - name: CREDENTIALS - Show organizational credentials list (formatted)
      ansible.builtin.debug:
        var: controller_objects_credentials_organizational
      when: >
            controller_objects_credentials_organizational is defined and
            controller_objects_credentials_organizational

    - name: CREDENTIALS - Show personal credentials list (formatted)
      ansible.builtin.debug:
        var: controller_objects_credentials_personal
      when: >
            controller_objects_credentials_personal is defined and
            controller_objects_credentials_personal
