---
- name: SCHEDULES - Audit schedules
  hosts: localhost
  gather_facts: false

  tasks:
    - name: SCHEDULES - Build list with all schedules
      ansible.builtin.set_fact:
        controller_objects_schedules: "{{ controller_objects_schedules | default([]) +
                                          [{'name': item.name,
                                            'descr': item.description,
                                            'template': item.summary_fields.unified_job_template.name,
                                            'rules': item.rrule} |
                                             regex_replace('\n', '')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'schedules/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | ee: {{ item.name }}"

    - name: SCHEDULES - Show schedules (formatted)
      ansible.builtin.debug:
        var: controller_objects_schedules
      when: >
            controller_objects_schedules | default('') and
            not show_vars_at_the_end | default(false)
