---
- name: ORGANIZATIONS - Audit AAP organizations
  hosts: localhost
  gather_facts: false

  tasks:
    - name: ORGANIZATIONS - Build list with all organizations
      ansible.builtin.set_fact:
        controller_objects_organizations: "{{ controller_objects_organizations | default([]) +
                                              [{'name': item.name,
                                                'descr': item.description,
                                                'creds': lookup('ansible.controller.controller_api',
                                                                'organizations/' + item.id | string + '/galaxy_credentials/',
                                                                return_objects=false,
                                                                return_all=true).results |
                                                         selectattr('name') | map(attribute='name')} |
                                                 regex_replace('\n', '')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'organizations/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | org: {{ item.name }}"

    - name: ORGANIZATIONS - Show organizations (formatted)
      ansible.builtin.debug:
        var: controller_objects_organizations
      when: >
            controller_objects_organizations is defined and
            controller_objects_organizations
