---
- name: EXECUTION ENVIRONMENTS - Audit execution environments
  hosts: localhost
  gather_facts: false

  tasks:
    - name: EXECUTION ENVIRONMENTS - Build list with all execution environments
      ansible.builtin.set_fact:
        controller_objects_execution_environments: |
                                                   {% if not item.pull %}
                                                   {{ controller_objects_execution_environments | default([]) +
                                                       [{'name': item.name,
                                                         'descr': item.description,
                                                         'image': item.image,
                                                         'pull': 'missing'} |
                                                          regex_replace('\n', '')] }}
                                                   {% else %}
                                                   {{ controller_objects_execution_environments | default([]) +
                                                       [{'name': item.name,
                                                         'descr': item.description,
                                                         'image': item.image,
                                                         'pull': item.pull} |
                                                          regex_replace('\n', '')] }}
                                                   {% endif %}
      loop: "{{ lookup('ansible.controller.controller_api', 'execution_environments/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | ee: {{ item.name }}"

    - name: EXECUTION ENVIRONMENTS - Show execution environments (formatted)
      ansible.builtin.debug:
        var: controller_objects_execution_environments
      when: >
            controller_objects_execution_environments | default('') and
            not show_vars_at_the_end | default(false)
