---
- name: Configure AAP
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Determine AAP version
      ansible.builtin.set_fact:
        controller_ping: "{{ lookup('ansible.controller.controller_api', 'ping') }}"
      tags:
        - controller_config
        - controller_config_settings
        - controller_config_all_apply
        - controller_config_all_cleanup
        - controller_config_credentials
        - controller_config_credentials_apply
        - controller_config_organizations
        - controller_config_organizations_cleanup
        - controller_config_organizations_apply
        - controller_config_users
        - controller_config_users_cleanup
        - controller_config_users_apply
        - controller_config_authentication
        - controller_config_authentication_cleanup
        - controller_config_authentication_apply
        - controller_config_teams
        - controller_config_teams_cleanup
        - controller_config_teams_apply
        - controller_config_roles
        - controller_config_roles_cleanup
        - controller_config_roles_apply

    - name: Make sure limit_organizations is a list (if defined)
      ansible.builtin.assert:
        that: limit_organizations | type_debug == "list"
        fail_msg: "Make sure limit_organizations is a list of organizations"
      when: limit_organizations is defined
      tags: always

  roles:
    - role: hub_config
      tags: hub_config
    - role: controller_config
      tags: controller_config
