---
- name: CREDENTIALS - Audit AAP credentials
  hosts: localhost
  gather_facts: false

  tasks:
    - name: CREDENTIALS - Get all credentials sources from AAP
      ansible.builtin.set_fact:
        aap_credential_sources: "{{ lookup('ansible.controller.controller_api', 'credential_input_sources/', return_objects=false, return_all=true).results }}"

    - name: CREDENTIALS - Get all credentials from AAP
      ansible.builtin.set_fact:
        controller_objects_credentials: "{{ controller_objects_credentials | default([]) +
                                            [{'name': item.name,
                                              'org': item.summary_fields.organization.name | default(''),
                                              'descr': item.description,
                                              'type': item.summary_fields.credential_type.name,
                                              'inputs': item.inputs,
                                              'src_input_field_name': aap_credential_sources |
                                                                      selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                      map(attribute='input_field_name') | last | default(''),
                                              'src_credential': aap_credential_sources |
                                                                selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                                map(attribute='summary_fields.source_credential.name') | last | default(''),
                                              'src_metadata':  aap_credential_sources |
                                                               selectattr('summary_fields.target_credential.name', 'equalto', item.name) |
                                                               map(attribute='metadata') | last | default('')} |
                                             regex_replace('\n', '') | replace('$encrypted$', 'HIDDEN')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'credentials/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | credential: {{ item.name }}"
      when: not item.managed

    - name: CREDENTIALS - Show credentials (formatted)
      ansible.builtin.debug:
        var: controller_objects_credentials
      when: >
            controller_objects_credentials | default('') and
            not show_vars_at_the_end | default(false)
